### ISSUE TITLE
Error: let tr in tablesAsJson

### ISSUE THREAD

**Issue by banghasan** [ipanardian/cekresi-cli#2]
gak jadi

**Comment by ipanardian** [comment]
Udah solved @banghasan? Bisa di share kenapa?

**Comment by banghasan** [comment]
1. saya test di local host bisa
2. saya push ke server vps error
3. ada 2 masalah :
   - masalah pada versi nodejs nya beda, saya gak tau minimal versi berapa. Bawaan server ubuntu lama (14.04 adalah versi 0.xxx). Jadinya saya sesuaikan dengan OS local (ubuntu 16.04),  install versi 4.x
   - masalah pada PhanthomJS, harus diinstall manual, waktu requirmen jsonnya ga ada sekalian.

itu share nya, semoga bermanfaat :-)
dan dokumentasinya diperbanyak :+1:

**Comment by ipanardian** [comment]
Makasih sharenya @banghasan, sangat bermanfaat
